=begin
#Plastiq Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PatchPaymentIntentRequestPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PatchPaymentIntentRequestPayload do
  let(:instance) { OpenapiClient::PatchPaymentIntentRequestPayload.new }

  describe 'test an instance of PatchPaymentIntentRequestPayload' do
    it 'should create an instance of PatchPaymentIntentRequestPayload' do
      expect(instance).to be_instance_of(OpenapiClient::PatchPaymentIntentRequestPayload)
    end
  end
  describe 'test attribute "target_amount"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
