/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Address model module.
 * @module model/Address
 * @version 1.0.0
 */
class Address {
    /**
     * Constructs a new <code>Address</code>.
     * @alias module:model/Address
     * @param line1 {String} Address line 1 (e.g., street, PO Box, or company name).
     * @param city {String} City, district, suburb, town, or village.
     * @param state {String} State, county, province, or region.
     * @param postalCode {String} ZIP or postal code.
     * @param country {String} Two-letter country code (ISO 3166-1 alpha-2).
     */
    constructor(line1, city, state, postalCode, country) { 
        
        Address.initialize(this, line1, city, state, postalCode, country);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, line1, city, state, postalCode, country) { 
        obj['line1'] = line1;
        obj['city'] = city;
        obj['state'] = state;
        obj['postalCode'] = postalCode;
        obj['country'] = country;
    }

    /**
     * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Address} obj Optional instance to populate.
     * @return {module:model/Address} The populated <code>Address</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Address();

            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
            if (data.hasOwnProperty('line2')) {
                obj['line2'] = ApiClient.convertToType(data['line2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Address line 1 (e.g., street, PO Box, or company name).
 * @member {String} line1
 */
Address.prototype['line1'] = undefined;

/**
 * Address line 2 (e.g., apartment, suite, unit, or building).
 * @member {String} line2
 */
Address.prototype['line2'] = undefined;

/**
 * City, district, suburb, town, or village.
 * @member {String} city
 */
Address.prototype['city'] = undefined;

/**
 * State, county, province, or region.
 * @member {String} state
 */
Address.prototype['state'] = undefined;

/**
 * ZIP or postal code.
 * @member {String} postalCode
 */
Address.prototype['postalCode'] = undefined;

/**
 * Two-letter country code (ISO 3166-1 alpha-2).
 * @member {String} country
 */
Address.prototype['country'] = undefined;






export default Address;

