/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactOneOf model module.
 * @module model/ContactOneOf
 * @version 1.0.0
 */
class ContactOneOf {
    /**
     * Constructs a new <code>ContactOneOf</code>.
     * @alias module:model/ContactOneOf
     * @param phone {String} 
     */
    constructor(phone) { 
        
        ContactOneOf.initialize(this, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone) { 
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>ContactOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactOneOf} obj Optional instance to populate.
     * @return {module:model/ContactOneOf} The populated <code>ContactOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactOneOf();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstName
 */
ContactOneOf.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
ContactOneOf.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
ContactOneOf.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
ContactOneOf.prototype['phone'] = undefined;






export default ContactOneOf;

