/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentIntentId from './PaymentIntentId';

/**
 * The CreateDocumentUploadRequestOneOf model module.
 * @module model/CreateDocumentUploadRequestOneOf
 * @version 1.0.0
 */
class CreateDocumentUploadRequestOneOf {
    /**
     * Constructs a new <code>CreateDocumentUploadRequestOneOf</code>.
     * @alias module:model/CreateDocumentUploadRequestOneOf
     */
    constructor() { 
        
        CreateDocumentUploadRequestOneOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateDocumentUploadRequestOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDocumentUploadRequestOneOf} obj Optional instance to populate.
     * @return {module:model/CreateDocumentUploadRequestOneOf} The populated <code>CreateDocumentUploadRequestOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDocumentUploadRequestOneOf();

            if (data.hasOwnProperty('paymentIntent')) {
                obj['paymentIntent'] = PaymentIntentId.constructFromObject(data['paymentIntent']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaymentIntentId} paymentIntent
 */
CreateDocumentUploadRequestOneOf.prototype['paymentIntent'] = undefined;






export default CreateDocumentUploadRequestOneOf;

