/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The PatchCard model module.
 * @module model/PatchCard
 * @version 1.0.0
 */
class PatchCard {
    /**
     * Constructs a new <code>PatchCard</code>.
     * Debit or Credit Card
     * @alias module:model/PatchCard
     * @param cvv {String} 3-4 digits
     */
    constructor(cvv) { 
        
        PatchCard.initialize(this, cvv);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cvv) { 
        obj['cvv'] = cvv;
    }

    /**
     * Constructs a <code>PatchCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchCard} obj Optional instance to populate.
     * @return {module:model/PatchCard} The populated <code>PatchCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchCard();

            if (data.hasOwnProperty('cardHolderName')) {
                obj['cardHolderName'] = ApiClient.convertToType(data['cardHolderName'], 'String');
            }
            if (data.hasOwnProperty('cvv')) {
                obj['cvv'] = ApiClient.convertToType(data['cvv'], 'String');
            }
            if (data.hasOwnProperty('expirationMonth')) {
                obj['expirationMonth'] = ApiClient.convertToType(data['expirationMonth'], 'String');
            }
            if (data.hasOwnProperty('expirationYear')) {
                obj['expirationYear'] = ApiClient.convertToType(data['expirationYear'], 'String');
            }
            if (data.hasOwnProperty('billingAddress')) {
                obj['billingAddress'] = ApiClient.convertToType(data['billingAddress'], Address);
            }
        }
        return obj;
    }


}

/**
 * @member {String} cardHolderName
 */
PatchCard.prototype['cardHolderName'] = undefined;

/**
 * 3-4 digits
 * @member {String} cvv
 */
PatchCard.prototype['cvv'] = undefined;

/**
 * @member {String} expirationMonth
 */
PatchCard.prototype['expirationMonth'] = undefined;

/**
 * @member {String} expirationYear
 */
PatchCard.prototype['expirationYear'] = undefined;

/**
 * @member {module:model/Address} billingAddress
 */
PatchCard.prototype['billingAddress'] = undefined;






export default PatchCard;

