/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentStatus.
* @enum {}
* @readonly
*/
export default class PaymentStatus {
    
        /**
         * value: "SUBMITTED"
         * @const
         */
        "SUBMITTED" = "SUBMITTED";

    
        /**
         * value: "COMMITTED"
         * @const
         */
        "COMMITTED" = "COMMITTED";

    
        /**
         * value: "DEPOSITED"
         * @const
         */
        "DEPOSITED" = "DEPOSITED";

    
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED" = "CANCELLED";

    

    /**
    * Returns a <code>PaymentStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentStatus} The enum <code>PaymentStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

