/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AmountDetails from './AmountDetails';
import PayerId from './PayerId';
import PaymentDetails from './PaymentDetails';
import PaymentIntentFees from './PaymentIntentFees';
import PaymentMethodId from './PaymentMethodId';
import RecipientId from './RecipientId';

/**
 * The PaymentIntent model module.
 * @module model/PaymentIntent
 * @version 1.0.0
 */
class PaymentIntent {
    /**
     * Constructs a new <code>PaymentIntent</code>.
     * @alias module:model/PaymentIntent
     */
    constructor() { 
        
        PaymentIntent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentIntent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentIntent} obj Optional instance to populate.
     * @return {module:model/PaymentIntent} The populated <code>PaymentIntent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentIntent();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('fees')) {
                obj['fees'] = ApiClient.convertToType(data['fees'], [PaymentIntentFees]);
            }
            if (data.hasOwnProperty('sourceAmount')) {
                obj['sourceAmount'] = ApiClient.convertToType(data['sourceAmount'], AmountDetails);
            }
            if (data.hasOwnProperty('targetAmount')) {
                obj['targetAmount'] = ApiClient.convertToType(data['targetAmount'], AmountDetails);
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = PaymentMethodId.constructFromObject(data['paymentMethod']);
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = RecipientId.constructFromObject(data['recipient']);
            }
            if (data.hasOwnProperty('payer')) {
                obj['payer'] = PayerId.constructFromObject(data['payer']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = PaymentDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('statusReasons')) {
                obj['statusReasons'] = ApiClient.convertToType(data['statusReasons'], [Object]);
            }
            if (data.hasOwnProperty('deliveryDate')) {
                obj['deliveryDate'] = ApiClient.convertToType(data['deliveryDate'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('expiresAt')) {
                obj['expiresAt'] = ApiClient.convertToType(data['expiresAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PaymentIntent.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/PaymentIntentFees>} fees
 */
PaymentIntent.prototype['fees'] = undefined;

/**
 * @member {module:model/AmountDetails} sourceAmount
 */
PaymentIntent.prototype['sourceAmount'] = undefined;

/**
 * @member {module:model/AmountDetails} targetAmount
 */
PaymentIntent.prototype['targetAmount'] = undefined;

/**
 * @member {module:model/PaymentMethodId} paymentMethod
 */
PaymentIntent.prototype['paymentMethod'] = undefined;

/**
 * @member {module:model/RecipientId} recipient
 */
PaymentIntent.prototype['recipient'] = undefined;

/**
 * @member {module:model/PayerId} payer
 */
PaymentIntent.prototype['payer'] = undefined;

/**
 * @member {module:model/PaymentDetails} details
 */
PaymentIntent.prototype['details'] = undefined;

/**
 * @member {module:model/PaymentIntent.StatusEnum} status
 */
PaymentIntent.prototype['status'] = undefined;

/**
 * @member {Array.<Object>} statusReasons
 */
PaymentIntent.prototype['statusReasons'] = undefined;

/**
 * @member {Date} deliveryDate
 */
PaymentIntent.prototype['deliveryDate'] = undefined;

/**
 * @member {Date} createdAt
 */
PaymentIntent.prototype['createdAt'] = undefined;

/**
 * @member {Date} expiresAt
 */
PaymentIntent.prototype['expiresAt'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PaymentIntent['StatusEnum'] = {

    /**
     * value: "CAPTURABLE"
     * @const
     */
    "CAPTURABLE": "CAPTURABLE",

    /**
     * value: "CAPTURED"
     * @const
     */
    "CAPTURED": "CAPTURED",

    /**
     * value: "EXPIRED"
     * @const
     */
    "EXPIRED": "EXPIRED",

    /**
     * value: "UNCAPTURABLE"
     * @const
     */
    "UNCAPTURABLE": "UNCAPTURABLE"
};



export default PaymentIntent;

