/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfACHCheckEFT from './OneOfACHCheckEFT';
import RecipientAddress from './RecipientAddress';
import RecipientContact from './RecipientContact';
import Status from './Status';

/**
 * The Recipient model module.
 * @module model/Recipient
 * @version 1.0.0
 */
class Recipient {
    /**
     * Constructs a new <code>Recipient</code>.
     * @alias module:model/Recipient
     */
    constructor() { 
        
        Recipient.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Recipient</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Recipient} obj Optional instance to populate.
     * @return {module:model/Recipient} The populated <code>Recipient</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Recipient();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('businessName')) {
                obj['businessName'] = ApiClient.convertToType(data['businessName'], 'String');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'String');
            }
            if (data.hasOwnProperty('businessAddress')) {
                obj['businessAddress'] = ApiClient.convertToType(data['businessAddress'], RecipientAddress);
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = RecipientContact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('receivingMethod')) {
                obj['receivingMethod'] = ApiClient.convertToType(data['receivingMethod'], OneOfACHCheckEFT);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Status);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Recipient.prototype['id'] = undefined;

/**
 * @member {String} businessName
 */
Recipient.prototype['businessName'] = undefined;

/**
 * @member {String} categoryId
 */
Recipient.prototype['categoryId'] = undefined;

/**
 * @member {module:model/RecipientAddress} businessAddress
 */
Recipient.prototype['businessAddress'] = undefined;

/**
 * @member {module:model/RecipientContact} contact
 */
Recipient.prototype['contact'] = undefined;

/**
 * @member {module:model/OneOfACHCheckEFT} receivingMethod
 */
Recipient.prototype['receivingMethod'] = undefined;

/**
 * @member {Date} createdAt
 */
Recipient.prototype['createdAt'] = undefined;

/**
 * @member {module:model/Status} status
 */
Recipient.prototype['status'] = undefined;






export default Recipient;

