/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatusReason model module.
 * @module model/StatusReason
 * @version 1.0.0
 */
class StatusReason {
    /**
     * Constructs a new <code>StatusReason</code>.
     * Used to provide more context in reference to the status response
     * @alias module:model/StatusReason
     */
    constructor() { 
        
        StatusReason.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatusReason</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusReason} obj Optional instance to populate.
     * @return {module:model/StatusReason} The populated <code>StatusReason</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusReason();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
StatusReason.prototype['code'] = undefined;

/**
 * @member {String} message
 */
StatusReason.prototype['message'] = undefined;






export default StatusReason;

