/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreatePayerRequest from '../model/CreatePayerRequest';
import Error from '../model/Error';
import Payer from '../model/Payer';
import UpdatePayerRequest from '../model/UpdatePayerRequest';

/**
* Payers service.
* @module api/PayersApi
* @version 1.0.0
*/
export default class PayersApi {

    /**
    * Constructs a new PayersApi. 
    * @alias module:api/PayersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Delete a Payer
     * @param {String} id The ID of the Payer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    payersIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payersIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/payers/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a Payer
     * @param {String} id The ID of the Payer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    payersIdDelete(id) {
      return this.payersIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve a Payer
     * @param {String} id The ID of the Payer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Payer} and HTTP response
     */
    payersIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payersIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Payer;
      return this.apiClient.callApi(
        '/payers/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve a Payer
     * @param {String} id The ID of the Payer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Payer}
     */
    payersIdGet(id) {
      return this.payersIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a Payer
     * @param {String} id The ID of the Payer
     * @param {module:model/UpdatePayerRequest} updatePayerRequest Payer to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Payer} and HTTP response
     */
    payersIdPatchWithHttpInfo(id, updatePayerRequest) {
      let postBody = updatePayerRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payersIdPatch");
      }
      // verify the required parameter 'updatePayerRequest' is set
      if (updatePayerRequest === undefined || updatePayerRequest === null) {
        throw new Error("Missing the required parameter 'updatePayerRequest' when calling payersIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Payer;
      return this.apiClient.callApi(
        '/payers/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a Payer
     * @param {String} id The ID of the Payer
     * @param {module:model/UpdatePayerRequest} updatePayerRequest Payer to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Payer}
     */
    payersIdPatch(id, updatePayerRequest) {
      return this.payersIdPatchWithHttpInfo(id, updatePayerRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a Payer
     * @param {module:model/CreatePayerRequest} createPayerRequest Payer to create
     * @param {Object} opts Optional parameters
     * @param {String} opts.traceId A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.
     * @param {String} opts.userAgent A string representing the User Agent. Required only when the request is not coming from the end user's browser.
     * @param {String} opts.endUserDeviceId A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.
     * @param {String} opts.endUserIp The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Payer} and HTTP response
     */
    payersPostWithHttpInfo(createPayerRequest, opts) {
      opts = opts || {};
      let postBody = createPayerRequest;
      // verify the required parameter 'createPayerRequest' is set
      if (createPayerRequest === undefined || createPayerRequest === null) {
        throw new Error("Missing the required parameter 'createPayerRequest' when calling payersPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Trace-Id': opts['traceId'],
        'User-Agent': opts['userAgent'],
        'End-User-Device-Id': opts['endUserDeviceId'],
        'End-User-Ip': opts['endUserIp']
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Payer;
      return this.apiClient.callApi(
        '/payers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a Payer
     * @param {module:model/CreatePayerRequest} createPayerRequest Payer to create
     * @param {Object} opts Optional parameters
     * @param {String} opts.traceId A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.
     * @param {String} opts.userAgent A string representing the User Agent. Required only when the request is not coming from the end user's browser.
     * @param {String} opts.endUserDeviceId A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.
     * @param {String} opts.endUserIp The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Payer}
     */
    payersPost(createPayerRequest, opts) {
      return this.payersPostWithHttpInfo(createPayerRequest, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
