=begin
#Plastiq Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/ach'
require 'openapi_client/models/address'
require 'openapi_client/models/amount_details'
require 'openapi_client/models/bank_account'
require 'openapi_client/models/bank_account_response'
require 'openapi_client/models/card'
require 'openapi_client/models/card_response'
require 'openapi_client/models/category'
require 'openapi_client/models/check'
require 'openapi_client/models/contact'
require 'openapi_client/models/contact_one_of'
require 'openapi_client/models/create_document_upload_request'
require 'openapi_client/models/create_document_upload_request_one_of'
require 'openapi_client/models/create_document_upload_request_one_of1'
require 'openapi_client/models/create_document_upload_request_one_of2'
require 'openapi_client/models/create_payer_request'
require 'openapi_client/models/create_payment_intent_request_payload'
require 'openapi_client/models/create_payment_method_request'
require 'openapi_client/models/create_payment_request'
require 'openapi_client/models/create_payment_request_from_id'
require 'openapi_client/models/create_recipient_request'
require 'openapi_client/models/create_recipient_request_contact'
require 'openapi_client/models/document_upload'
require 'openapi_client/models/document_upload_metadata'
require 'openapi_client/models/eft'
require 'openapi_client/models/error'
require 'openapi_client/models/error_errors'
require 'openapi_client/models/id'
require 'openapi_client/models/identity_document_response'
require 'openapi_client/models/identity_documents'
require 'openapi_client/models/inline_object'
require 'openapi_client/models/inline_response200'
require 'openapi_client/models/inline_response2001'
require 'openapi_client/models/inline_response2002'
require 'openapi_client/models/inline_response2003'
require 'openapi_client/models/inline_response2004'
require 'openapi_client/models/pagination_object'
require 'openapi_client/models/patch_bank_account'
require 'openapi_client/models/patch_card'
require 'openapi_client/models/patch_payment_intent_request_payload'
require 'openapi_client/models/patch_payment_method_request'
require 'openapi_client/models/patch_recipient_request'
require 'openapi_client/models/payer'
require 'openapi_client/models/payer_id'
require 'openapi_client/models/payment'
require 'openapi_client/models/payment_details'
require 'openapi_client/models/payment_id'
require 'openapi_client/models/payment_intent'
require 'openapi_client/models/payment_intent_fees'
require 'openapi_client/models/payment_intent_id'
require 'openapi_client/models/payment_method'
require 'openapi_client/models/payment_method_id'
require 'openapi_client/models/payment_method_status'
require 'openapi_client/models/payment_refund'
require 'openapi_client/models/payment_refund_request'
require 'openapi_client/models/payment_status'
require 'openapi_client/models/recipient'
require 'openapi_client/models/recipient_address'
require 'openapi_client/models/recipient_contact'
require 'openapi_client/models/recipient_id'
require 'openapi_client/models/status'
require 'openapi_client/models/status_reason'
require 'openapi_client/models/update_payer_request'
require 'openapi_client/models/wire'

# APIs
require 'openapi_client/api/categories_api'
require 'openapi_client/api/client_secrets_api'
require 'openapi_client/api/documents_api'
require 'openapi_client/api/payers_api'
require 'openapi_client/api/payment_methods_api'
require 'openapi_client/api/payments_api'
require 'openapi_client/api/recipients_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
