/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The BankAccountResponse model module.
 * @module model/BankAccountResponse
 * @version 1.0.0
 */
class BankAccountResponse {
    /**
     * Constructs a new <code>BankAccountResponse</code>.
     * @alias module:model/BankAccountResponse
     */
    constructor() { 
        
        BankAccountResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BankAccountResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankAccountResponse} obj Optional instance to populate.
     * @return {module:model/BankAccountResponse} The populated <code>BankAccountResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankAccountResponse();

            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = ApiClient.convertToType(data['accountType'], 'String');
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('accountLastFour')) {
                obj['accountLastFour'] = ApiClient.convertToType(data['accountLastFour'], 'String');
            }
            if (data.hasOwnProperty('routingNumber')) {
                obj['routingNumber'] = ApiClient.convertToType(data['routingNumber'], 'String');
            }
            if (data.hasOwnProperty('billingAddress')) {
                obj['billingAddress'] = ApiClient.convertToType(data['billingAddress'], Address);
            }
        }
        return obj;
    }


}

/**
 * The type of the bank account
 * @member {module:model/BankAccountResponse.AccountTypeEnum} accountType
 */
BankAccountResponse.prototype['accountType'] = undefined;

/**
 * The legal name of the account holder
 * @member {String} accountHolderName
 */
BankAccountResponse.prototype['accountHolderName'] = undefined;

/**
 * @member {String} createdAt
 */
BankAccountResponse.prototype['createdAt'] = undefined;

/**
 * Last 4 digits of the account number
 * @member {String} accountLastFour
 */
BankAccountResponse.prototype['accountLastFour'] = undefined;

/**
 * The routing number of the bank account
 * @member {String} routingNumber
 */
BankAccountResponse.prototype['routingNumber'] = undefined;

/**
 * @member {module:model/Address} billingAddress
 */
BankAccountResponse.prototype['billingAddress'] = undefined;





/**
 * Allowed values for the <code>accountType</code> property.
 * @enum {String}
 * @readonly
 */
BankAccountResponse['AccountTypeEnum'] = {

    /**
     * value: "CHECKING"
     * @const
     */
    "CHECKING": "CHECKING",

    /**
     * value: "SAVINGS"
     * @const
     */
    "SAVINGS": "SAVINGS"
};



export default BankAccountResponse;

