/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityDocumentResponse model module.
 * @module model/IdentityDocumentResponse
 * @version 1.0.0
 */
class IdentityDocumentResponse {
    /**
     * Constructs a new <code>IdentityDocumentResponse</code>.
     * @alias module:model/IdentityDocumentResponse
     */
    constructor() { 
        
        IdentityDocumentResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentityDocumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityDocumentResponse} obj Optional instance to populate.
     * @return {module:model/IdentityDocumentResponse} The populated <code>IdentityDocumentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityDocumentResponse();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/IdentityDocumentResponse.TypeEnum} type
 */
IdentityDocumentResponse.prototype['type'] = undefined;

/**
 * @member {String} id
 */
IdentityDocumentResponse.prototype['id'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
IdentityDocumentResponse['TypeEnum'] = {

    /**
     * value: "US_TIN"
     * @const
     */
    "US_TIN": "US_TIN",

    /**
     * value: "US_EIN"
     * @const
     */
    "US_EIN": "US_EIN",

    /**
     * value: "US_SSN"
     * @const
     */
    "US_SSN": "US_SSN",

    /**
     * value: "PASSPORT_NUMBER"
     * @const
     */
    "PASSPORT_NUMBER": "PASSPORT_NUMBER",

    /**
     * value: "ALIEN_REGISTRATION_NUMBER"
     * @const
     */
    "ALIEN_REGISTRATION_NUMBER": "ALIEN_REGISTRATION_NUMBER"
};



export default IdentityDocumentResponse;

