/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Contact from './Contact';
import IdentityDocumentResponse from './IdentityDocumentResponse';
import Status from './Status';

/**
 * The Payer model module.
 * @module model/Payer
 * @version 1.0.0
 */
class Payer {
    /**
     * Constructs a new <code>Payer</code>.
     * @alias module:model/Payer
     */
    constructor() { 
        
        Payer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Payer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payer} obj Optional instance to populate.
     * @return {module:model/Payer} The populated <code>Payer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payer();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('businessName')) {
                obj['businessName'] = ApiClient.convertToType(data['businessName'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('businessAddress')) {
                obj['businessAddress'] = ApiClient.convertToType(data['businessAddress'], Address);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Status);
            }
            if (data.hasOwnProperty('identityDocuments')) {
                obj['identityDocuments'] = ApiClient.convertToType(data['identityDocuments'], [IdentityDocumentResponse]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Payer.prototype['id'] = undefined;

/**
 * @member {String} businessName
 */
Payer.prototype['businessName'] = undefined;

/**
 * @member {module:model/Contact} contact
 */
Payer.prototype['contact'] = undefined;

/**
 * @member {module:model/Address} businessAddress
 */
Payer.prototype['businessAddress'] = undefined;

/**
 * @member {Date} createdAt
 */
Payer.prototype['createdAt'] = undefined;

/**
 * @member {module:model/Status} status
 */
Payer.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/IdentityDocumentResponse>} identityDocuments
 */
Payer.prototype['identityDocuments'] = undefined;






export default Payer;

