/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentRefundRequest model module.
 * @module model/PaymentRefundRequest
 * @version 1.0.0
 */
class PaymentRefundRequest {
    /**
     * Constructs a new <code>PaymentRefundRequest</code>.
     * @alias module:model/PaymentRefundRequest
     */
    constructor() { 
        
        PaymentRefundRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentRefundRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRefundRequest} obj Optional instance to populate.
     * @return {module:model/PaymentRefundRequest} The populated <code>PaymentRefundRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRefundRequest();

            if (data.hasOwnProperty('payerId')) {
                obj['payerId'] = ApiClient.convertToType(data['payerId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The ID of the Payer the Payment to refund belongs to
 * @member {String} payerId
 */
PaymentRefundRequest.prototype['payerId'] = undefined;






export default PaymentRefundRequest;

