/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlastiqPublicApi);
  }
}(this, function(expect, PlastiqPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlastiqPublicApi.PaymentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentsApi', function() {
    describe('paymentIntentsIdGet', function() {
      it('should call paymentIntentsIdGet successfully', function(done) {
        //uncomment below and update the code to test paymentIntentsIdGet
        //instance.paymentIntentsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentIntentsIdPatch', function() {
      it('should call paymentIntentsIdPatch successfully', function(done) {
        //uncomment below and update the code to test paymentIntentsIdPatch
        //instance.paymentIntentsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentIntentsPost', function() {
      it('should call paymentIntentsPost successfully', function(done) {
        //uncomment below and update the code to test paymentIntentsPost
        //instance.paymentIntentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsGet', function() {
      it('should call paymentsGet successfully', function(done) {
        //uncomment below and update the code to test paymentsGet
        //instance.paymentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdGet', function() {
      it('should call paymentsIdGet successfully', function(done) {
        //uncomment below and update the code to test paymentsIdGet
        //instance.paymentsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdRefundsPost', function() {
      it('should call paymentsIdRefundsPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdRefundsPost
        //instance.paymentsIdRefundsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsPost', function() {
      it('should call paymentsPost successfully', function(done) {
        //uncomment below and update the code to test paymentsPost
        //instance.paymentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
