=begin
#Plastiq Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PaymentMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentMethodsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PaymentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'should create an instance of PaymentMethodsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PaymentMethodsApi)
    end
  end

  # unit tests for payment_methods_get
  # Retrieve a paginated list of Payment Methods by query parameter(s)
  # @param payer_id The associated Payer ID to list Payment Methods for
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset The number of records you wish to skip before selecting records
  # @option opts [Integer] :limit Number of items to return
  # @return [InlineResponse2003]
  describe 'payment_methods_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_id_delete
  # Delete a Payment Method
  # @param id The ID of the Payment Method
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_methods_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_id_get
  # Retrieve a Payment Method
  # @param payer_id The Payer ID associated to the Payment Method
  # @param id The ID of the Payment Method
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethod]
  describe 'payment_methods_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_id_patch
  # Update a Payment Method
  # @param id The ID of the Payment Method
  # @param patch_payment_method_request Payment Method to update
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trace_id A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.
  # @option opts [String] :user_agent A string representing the User Agent. Required only when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_device_id A unique identifier for the end user&#39;s browser. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_ip The IP address of the end user. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @return [PaymentMethod]
  describe 'payment_methods_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_post
  # Create a Payment Method
  # @param create_payment_method_request Payment Method to create
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trace_id A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.
  # @option opts [String] :user_agent A string representing the User Agent. Required only when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_device_id A unique identifier for the end user&#39;s browser. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_ip The IP address of the end user. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @return [PaymentMethod]
  describe 'payment_methods_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
