=begin
#Plastiq Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ClientSecretsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClientSecretsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ClientSecretsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientSecretsApi' do
    it 'should create an instance of ClientSecretsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ClientSecretsApi)
    end
  end

  # unit tests for client_secrets_post
  # Create a single-use Client Secret
  # @param inline_object 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trace_id A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.
  # @option opts [String] :user_agent A string representing the User Agent. Required only when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_device_id A unique identifier for the end user&#39;s browser. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @option opts [String] :end_user_ip The IP address of the end user. Recommended for compliance when the request is not coming from the end user&#39;s browser.
  # @return [InlineResponse2001]
  describe 'client_secrets_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
