/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The Card model module.
 * @module model/Card
 * @version 1.0.0
 */
class Card {
    /**
     * Constructs a new <code>Card</code>.
     * Debit or Credit Card
     * @alias module:model/Card
     * @param cardHolderName {String} 
     * @param accountNumber {String} Card number.
     * @param cvv {String} 3-4 digits
     * @param expirationMonth {String} 
     * @param expirationYear {String} 
     * @param billingAddress {module:model/Address} 
     */
    constructor(cardHolderName, accountNumber, cvv, expirationMonth, expirationYear, billingAddress) { 
        
        Card.initialize(this, cardHolderName, accountNumber, cvv, expirationMonth, expirationYear, billingAddress);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cardHolderName, accountNumber, cvv, expirationMonth, expirationYear, billingAddress) { 
        obj['cardHolderName'] = cardHolderName;
        obj['accountNumber'] = accountNumber;
        obj['cvv'] = cvv;
        obj['expirationMonth'] = expirationMonth;
        obj['expirationYear'] = expirationYear;
        obj['billingAddress'] = billingAddress;
    }

    /**
     * Constructs a <code>Card</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Card} obj Optional instance to populate.
     * @return {module:model/Card} The populated <code>Card</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Card();

            if (data.hasOwnProperty('cardHolderName')) {
                obj['cardHolderName'] = ApiClient.convertToType(data['cardHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('cvv')) {
                obj['cvv'] = ApiClient.convertToType(data['cvv'], 'String');
            }
            if (data.hasOwnProperty('expirationMonth')) {
                obj['expirationMonth'] = ApiClient.convertToType(data['expirationMonth'], 'String');
            }
            if (data.hasOwnProperty('expirationYear')) {
                obj['expirationYear'] = ApiClient.convertToType(data['expirationYear'], 'String');
            }
            if (data.hasOwnProperty('billingAddress')) {
                obj['billingAddress'] = ApiClient.convertToType(data['billingAddress'], Address);
            }
        }
        return obj;
    }


}

/**
 * @member {String} cardHolderName
 */
Card.prototype['cardHolderName'] = undefined;

/**
 * Card number.
 * @member {String} accountNumber
 */
Card.prototype['accountNumber'] = undefined;

/**
 * 3-4 digits
 * @member {String} cvv
 */
Card.prototype['cvv'] = undefined;

/**
 * @member {String} expirationMonth
 */
Card.prototype['expirationMonth'] = undefined;

/**
 * @member {String} expirationYear
 */
Card.prototype['expirationYear'] = undefined;

/**
 * @member {module:model/Address} billingAddress
 */
Card.prototype['billingAddress'] = undefined;






export default Card;

