/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactOneOf from './ContactOneOf';
import CreateRecipientRequestContact from './CreateRecipientRequestContact';

/**
 * The Contact model module.
 * @module model/Contact
 * @version 1.0.0
 */
class Contact {
    /**
     * Constructs a new <code>Contact</code>.
     * @alias module:model/Contact
     * @implements module:model/CreateRecipientRequestContact
     * @implements module:model/ContactOneOf
     * @param email {String} 
     * @param phone {String} 
     */
    constructor(email, phone) { 
        CreateRecipientRequestContact.initialize(this, email);ContactOneOf.initialize(this, phone);
        Contact.initialize(this, email, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, phone) { 
        obj['email'] = email;
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>Contact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Contact} obj Optional instance to populate.
     * @return {module:model/Contact} The populated <code>Contact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contact();
            CreateRecipientRequestContact.constructFromObject(data, obj);
            ContactOneOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstName
 */
Contact.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
Contact.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
Contact.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
Contact.prototype['phone'] = undefined;


// Implement CreateRecipientRequestContact interface:
/**
 * @member {String} firstName
 */
CreateRecipientRequestContact.prototype['firstName'] = undefined;
/**
 * @member {String} lastName
 */
CreateRecipientRequestContact.prototype['lastName'] = undefined;
/**
 * @member {String} email
 */
CreateRecipientRequestContact.prototype['email'] = undefined;
/**
 * @member {String} phone
 */
CreateRecipientRequestContact.prototype['phone'] = undefined;
// Implement ContactOneOf interface:
/**
 * @member {String} firstName
 */
ContactOneOf.prototype['firstName'] = undefined;
/**
 * @member {String} lastName
 */
ContactOneOf.prototype['lastName'] = undefined;
/**
 * @member {String} email
 */
ContactOneOf.prototype['email'] = undefined;
/**
 * @member {String} phone
 */
ContactOneOf.prototype['phone'] = undefined;




export default Contact;

