/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Contact from './Contact';
import IdentityDocuments from './IdentityDocuments';

/**
 * The CreatePayerRequest model module.
 * @module model/CreatePayerRequest
 * @version 1.0.0
 */
class CreatePayerRequest {
    /**
     * Constructs a new <code>CreatePayerRequest</code>.
     * @alias module:model/CreatePayerRequest
     * @param contact {module:model/Contact} 
     */
    constructor(contact) { 
        
        CreatePayerRequest.initialize(this, contact);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contact) { 
        obj['contact'] = contact;
    }

    /**
     * Constructs a <code>CreatePayerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePayerRequest} obj Optional instance to populate.
     * @return {module:model/CreatePayerRequest} The populated <code>CreatePayerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePayerRequest();

            if (data.hasOwnProperty('businessName')) {
                obj['businessName'] = ApiClient.convertToType(data['businessName'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('businessAddress')) {
                obj['businessAddress'] = ApiClient.convertToType(data['businessAddress'], Address);
            }
            if (data.hasOwnProperty('identityDocuments')) {
                obj['identityDocuments'] = ApiClient.convertToType(data['identityDocuments'], [IdentityDocuments]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} businessName
 */
CreatePayerRequest.prototype['businessName'] = undefined;

/**
 * @member {module:model/Contact} contact
 */
CreatePayerRequest.prototype['contact'] = undefined;

/**
 * @member {module:model/Address} businessAddress
 */
CreatePayerRequest.prototype['businessAddress'] = undefined;

/**
 * @member {Array.<module:model/IdentityDocuments>} identityDocuments
 */
CreatePayerRequest.prototype['identityDocuments'] = undefined;






export default CreatePayerRequest;

