/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaginationObject model module.
 * @module model/PaginationObject
 * @version 1.0.0
 */
class PaginationObject {
    /**
     * Constructs a new <code>PaginationObject</code>.
     * @alias module:model/PaginationObject
     */
    constructor() { 
        
        PaginationObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginationObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginationObject} obj Optional instance to populate.
     * @return {module:model/PaginationObject} The populated <code>PaginationObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationObject();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('hasNextPage')) {
                obj['hasNextPage'] = ApiClient.convertToType(data['hasNextPage'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offset
 */
PaginationObject.prototype['offset'] = undefined;

/**
 * @member {Number} limit
 */
PaginationObject.prototype['limit'] = undefined;

/**
 * @member {Number} total
 */
PaginationObject.prototype['total'] = undefined;

/**
 * @member {Boolean} hasNextPage
 */
PaginationObject.prototype['hasNextPage'] = undefined;






export default PaginationObject;

