/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfamountDetails from './OneOfamountDetails';
import PaymentDetails from './PaymentDetails';

/**
 * The PatchPaymentIntentRequestPayload model module.
 * @module model/PatchPaymentIntentRequestPayload
 * @version 1.0.0
 */
class PatchPaymentIntentRequestPayload {
    /**
     * Constructs a new <code>PatchPaymentIntentRequestPayload</code>.
     * @alias module:model/PatchPaymentIntentRequestPayload
     */
    constructor() { 
        
        PatchPaymentIntentRequestPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchPaymentIntentRequestPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchPaymentIntentRequestPayload} obj Optional instance to populate.
     * @return {module:model/PatchPaymentIntentRequestPayload} The populated <code>PatchPaymentIntentRequestPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchPaymentIntentRequestPayload();

            if (data.hasOwnProperty('targetAmount')) {
                obj['targetAmount'] = ApiClient.convertToType(data['targetAmount'], OneOfamountDetails);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = PaymentDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfamountDetails} targetAmount
 */
PatchPaymentIntentRequestPayload.prototype['targetAmount'] = undefined;

/**
 * @member {module:model/PaymentDetails} details
 */
PatchPaymentIntentRequestPayload.prototype['details'] = undefined;

/**
 * additional payment information to support operational requirements
 * @member {Object} metadata
 */
PatchPaymentIntentRequestPayload.prototype['metadata'] = undefined;






export default PatchPaymentIntentRequestPayload;

