/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfPatchCardPatchBankAccount from './OneOfPatchCardPatchBankAccount';
import PayerId from './PayerId';

/**
 * The PatchPaymentMethodRequest model module.
 * @module model/PatchPaymentMethodRequest
 * @version 1.0.0
 */
class PatchPaymentMethodRequest {
    /**
     * Constructs a new <code>PatchPaymentMethodRequest</code>.
     * @alias module:model/PatchPaymentMethodRequest
     * @param type {module:model/PatchPaymentMethodRequest.TypeEnum} 
     * @param data {module:model/OneOfPatchCardPatchBankAccount} 
     * @param payer {module:model/PayerId} 
     */
    constructor(type, data, payer) { 
        
        PatchPaymentMethodRequest.initialize(this, type, data, payer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, data, payer) { 
        obj['type'] = type;
        obj['data'] = data;
        obj['payer'] = payer;
    }

    /**
     * Constructs a <code>PatchPaymentMethodRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchPaymentMethodRequest} obj Optional instance to populate.
     * @return {module:model/PatchPaymentMethodRequest} The populated <code>PatchPaymentMethodRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchPaymentMethodRequest();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], OneOfPatchCardPatchBankAccount);
            }
            if (data.hasOwnProperty('payer')) {
                obj['payer'] = PayerId.constructFromObject(data['payer']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PatchPaymentMethodRequest.TypeEnum} type
 */
PatchPaymentMethodRequest.prototype['type'] = undefined;

/**
 * @member {module:model/OneOfPatchCardPatchBankAccount} data
 */
PatchPaymentMethodRequest.prototype['data'] = undefined;

/**
 * @member {module:model/PayerId} payer
 */
PatchPaymentMethodRequest.prototype['payer'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PatchPaymentMethodRequest['TypeEnum'] = {

    /**
     * value: "CARD"
     * @const
     */
    "CARD": "CARD",

    /**
     * value: "BANK_ACCOUNT"
     * @const
     */
    "BANK_ACCOUNT": "BANK_ACCOUNT"
};



export default PatchPaymentMethodRequest;

