/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchBankAccount model module.
 * @module model/PatchBankAccount
 * @version 1.0.0
 */
class PatchBankAccount {
    /**
     * Constructs a new <code>PatchBankAccount</code>.
     * Bank Account Funded
     * @alias module:model/PatchBankAccount
     */
    constructor() { 
        
        PatchBankAccount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchBankAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchBankAccount} obj Optional instance to populate.
     * @return {module:model/PatchBankAccount} The populated <code>PatchBankAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchBankAccount();

            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('routingNumber')) {
                obj['routingNumber'] = ApiClient.convertToType(data['routingNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The legal name of the account holder
 * @member {String} accountHolderName
 */
PatchBankAccount.prototype['accountHolderName'] = undefined;

/**
 * The routing number of the bank account
 * @member {String} routingNumber
 */
PatchBankAccount.prototype['routingNumber'] = undefined;






export default PatchBankAccount;

