/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PayerId model module.
 * @module model/PayerId
 * @version 1.0.0
 */
class PayerId {
    /**
     * Constructs a new <code>PayerId</code>.
     * @alias module:model/PayerId
     * @param id {String} 
     */
    constructor(id) { 
        
        PayerId.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>PayerId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayerId} obj Optional instance to populate.
     * @return {module:model/PayerId} The populated <code>PayerId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayerId();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PayerId.prototype['id'] = undefined;






export default PayerId;

