/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AmountDetails from './AmountDetails';
import PayerId from './PayerId';
import PaymentDetails from './PaymentDetails';
import PaymentIntentFees from './PaymentIntentFees';
import PaymentMethodId from './PaymentMethodId';
import PaymentStatus from './PaymentStatus';
import RecipientId from './RecipientId';

/**
 * The Payment model module.
 * @module model/Payment
 * @version 1.0.0
 */
class Payment {
    /**
     * Constructs a new <code>Payment</code>.
     * @alias module:model/Payment
     */
    constructor() { 
        
        Payment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Payment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payment} obj Optional instance to populate.
     * @return {module:model/Payment} The populated <code>Payment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('fees')) {
                obj['fees'] = ApiClient.convertToType(data['fees'], [PaymentIntentFees]);
            }
            if (data.hasOwnProperty('sourceAmount')) {
                obj['sourceAmount'] = ApiClient.convertToType(data['sourceAmount'], AmountDetails);
            }
            if (data.hasOwnProperty('targetAmount')) {
                obj['targetAmount'] = ApiClient.convertToType(data['targetAmount'], AmountDetails);
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = PaymentMethodId.constructFromObject(data['paymentMethod']);
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = RecipientId.constructFromObject(data['recipient']);
            }
            if (data.hasOwnProperty('payer')) {
                obj['payer'] = PayerId.constructFromObject(data['payer']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = PaymentDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('deliveryDate')) {
                obj['deliveryDate'] = ApiClient.convertToType(data['deliveryDate'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], PaymentStatus);
            }
            if (data.hasOwnProperty('sourceDescriptor')) {
                obj['sourceDescriptor'] = ApiClient.convertToType(data['sourceDescriptor'], 'String');
            }
            if (data.hasOwnProperty('targetDescriptor')) {
                obj['targetDescriptor'] = ApiClient.convertToType(data['targetDescriptor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Payment.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/PaymentIntentFees>} fees
 */
Payment.prototype['fees'] = undefined;

/**
 * @member {module:model/AmountDetails} sourceAmount
 */
Payment.prototype['sourceAmount'] = undefined;

/**
 * @member {module:model/AmountDetails} targetAmount
 */
Payment.prototype['targetAmount'] = undefined;

/**
 * @member {module:model/PaymentMethodId} paymentMethod
 */
Payment.prototype['paymentMethod'] = undefined;

/**
 * @member {module:model/RecipientId} recipient
 */
Payment.prototype['recipient'] = undefined;

/**
 * @member {module:model/PayerId} payer
 */
Payment.prototype['payer'] = undefined;

/**
 * @member {module:model/PaymentDetails} details
 */
Payment.prototype['details'] = undefined;

/**
 * @member {Date} deliveryDate
 */
Payment.prototype['deliveryDate'] = undefined;

/**
 * @member {Date} createdAt
 */
Payment.prototype['createdAt'] = undefined;

/**
 * @member {module:model/PaymentStatus} status
 */
Payment.prototype['status'] = undefined;

/**
 * @member {String} sourceDescriptor
 */
Payment.prototype['sourceDescriptor'] = undefined;

/**
 * @member {String} targetDescriptor
 */
Payment.prototype['targetDescriptor'] = undefined;






export default Payment;

