/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AmountDetails from './AmountDetails';

/**
 * The PaymentIntentFees model module.
 * @module model/PaymentIntentFees
 * @version 1.0.0
 */
class PaymentIntentFees {
    /**
     * Constructs a new <code>PaymentIntentFees</code>.
     * @alias module:model/PaymentIntentFees
     */
    constructor() { 
        
        PaymentIntentFees.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentIntentFees</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentIntentFees} obj Optional instance to populate.
     * @return {module:model/PaymentIntentFees} The populated <code>PaymentIntentFees</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentIntentFees();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], AmountDetails);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AmountDetails} amount
 */
PaymentIntentFees.prototype['amount'] = undefined;

/**
 * The type of fee applied to the payment
 * @member {module:model/PaymentIntentFees.TypeEnum} type
 */
PaymentIntentFees.prototype['type'] = undefined;

/**
 * The rate of the fee assessed, presented in percentage.
 * @member {String} rate
 */
PaymentIntentFees.prototype['rate'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentIntentFees['TypeEnum'] = {

    /**
     * value: "PLASTIQ_SERVICE_FEE"
     * @const
     */
    "SERVICE_FEE": "PLASTIQ_SERVICE_FEE",

    /**
     * value: "PLASTIQ_CROSS_BORDER_FEE"
     * @const
     */
    "CROSS_BORDER_FEE": "PLASTIQ_CROSS_BORDER_FEE"
};



export default PaymentIntentFees;

