/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecipientContact model module.
 * @module model/RecipientContact
 * @version 1.0.0
 */
class RecipientContact {
    /**
     * Constructs a new <code>RecipientContact</code>.
     * @alias module:model/RecipientContact
     */
    constructor() { 
        
        RecipientContact.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecipientContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecipientContact} obj Optional instance to populate.
     * @return {module:model/RecipientContact} The populated <code>RecipientContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipientContact();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstName
 */
RecipientContact.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
RecipientContact.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
RecipientContact.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
RecipientContact.prototype['phone'] = undefined;






export default RecipientContact;

