/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlastiqPublicApi);
  }
}(this, function(expect, PlastiqPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlastiqPublicApi.DocumentUploadMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentUploadMetadata', function() {
    it('should create an instance of DocumentUploadMetadata', function() {
      // uncomment below and update the code to test DocumentUploadMetadata
      //var instane = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be.a(PlastiqPublicApi.DocumentUploadMetadata);
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property successActionStatus (base name: "success_action_status")', function() {
      // uncomment below and update the code to test the property successActionStatus
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property bucket (base name: "bucket")', function() {
      // uncomment below and update the code to test the property bucket
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property xAmzAlgorithm (base name: "X-Amz-Algorithm")', function() {
      // uncomment below and update the code to test the property xAmzAlgorithm
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property xAmzCredential (base name: "X-Amz-Credential")', function() {
      // uncomment below and update the code to test the property xAmzCredential
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property xAmzDate (base name: "X-Amz-Date")', function() {
      // uncomment below and update the code to test the property xAmzDate
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property xAmzSecurityToken (base name: "X-Amz-Security-Token")', function() {
      // uncomment below and update the code to test the property xAmzSecurityToken
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property policy (base name: "Policy")', function() {
      // uncomment below and update the code to test the property policy
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

    it('should have the property xAmzSignature (base name: "X-Amz-Signature")', function() {
      // uncomment below and update the code to test the property xAmzSignature
      //var instance = new PlastiqPublicApi.DocumentUploadMetadata();
      //expect(instance).to.be();
    });

  });

}));
