/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlastiqPublicApi);
  }
}(this, function(expect, PlastiqPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlastiqPublicApi.Payment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Payment', function() {
    it('should create an instance of Payment', function() {
      // uncomment below and update the code to test Payment
      //var instane = new PlastiqPublicApi.Payment();
      //expect(instance).to.be.a(PlastiqPublicApi.Payment);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property fees (base name: "fees")', function() {
      // uncomment below and update the code to test the property fees
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property sourceAmount (base name: "sourceAmount")', function() {
      // uncomment below and update the code to test the property sourceAmount
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property targetAmount (base name: "targetAmount")', function() {
      // uncomment below and update the code to test the property targetAmount
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property recipient (base name: "recipient")', function() {
      // uncomment below and update the code to test the property recipient
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property payer (base name: "payer")', function() {
      // uncomment below and update the code to test the property payer
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property details (base name: "details")', function() {
      // uncomment below and update the code to test the property details
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property deliveryDate (base name: "deliveryDate")', function() {
      // uncomment below and update the code to test the property deliveryDate
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property sourceDescriptor (base name: "sourceDescriptor")', function() {
      // uncomment below and update the code to test the property sourceDescriptor
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

    it('should have the property targetDescriptor (base name: "targetDescriptor")', function() {
      // uncomment below and update the code to test the property targetDescriptor
      //var instance = new PlastiqPublicApi.Payment();
      //expect(instance).to.be();
    });

  });

}));
