/**
 * Plastiq Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlastiqPublicApi);
  }
}(this, function(expect, PlastiqPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlastiqPublicApi.Wire();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Wire', function() {
    it('should create an instance of Wire', function() {
      // uncomment below and update the code to test Wire
      //var instane = new PlastiqPublicApi.Wire();
      //expect(instance).to.be.a(PlastiqPublicApi.Wire);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new PlastiqPublicApi.Wire();
      //expect(instance).to.be();
    });

    it('should have the property accountNumber (base name: "accountNumber")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new PlastiqPublicApi.Wire();
      //expect(instance).to.be();
    });

    it('should have the property routingNumber (base name: "routingNumber")', function() {
      // uncomment below and update the code to test the property routingNumber
      //var instance = new PlastiqPublicApi.Wire();
      //expect(instance).to.be();
    });

    it('should have the property beneficiaryName (base name: "beneficiaryName")', function() {
      // uncomment below and update the code to test the property beneficiaryName
      //var instance = new PlastiqPublicApi.Wire();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new PlastiqPublicApi.Wire();
      //expect(instance).to.be();
    });

  });

}));
